export const INTERVIEW_DATA = [
    {
        department:1,
        name:'Shivam Singh',
        email:'shivam5@gmail.com',
        mobile_number:'89894904',
        round_type:'round_1',
        interview_date:'2023-03-04',
        interview_time:'22:09',
        final_status:'1',
    },
    {
        department:2,
        name:'Swapnil Maurya',
        email:'swapnil@gmail.com',
        mobile_number:'79867799',
        round_type:'round_2',
        interview_date:'2023-02-02',
        interview_time:'22:09',
        final_status:'2',
    },
    {
        department: 3,
        name:'Arpit Dwivedi',
        email:'arpit@gmail.com',
        mobile_number:'76769798',
        round_type:'round_5',
        interview_date:'2023-01-01',
        interview_time:'22:09',
        final_status:'3',
    },
    {
        department:4,
        name:'Rishab Ghildiyal',
        email:'swapnil@gmail.com',
        mobile_number:'79867799',
        round_type:'round_10',
        interview_date:'2023-02-10',
        interview_time:'22:09',
        final_status:'4',
    },
    {
        department:5,
        name:'Walter White',
        email:'walter@gmail.com',
        mobile_number:'69876978',
        round_type:'round_1',
        interview_date:'2023-02-05',
        interview_time:'22:09',
        final_status:'1',
    },
    {
        department:6,
        name:'Jesse Pinkman',
        email:'jesse@gmail.com',
        mobile_number:'79867799',
        round_type:'round_3',
        interview_date:'2023-01-06',
        interview_time:'22:09',
        final_status:'3',
    },
    
]