openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in HTML.
  version: 1.0.0
servers:
paths:
  /login:
    post:
      summary: login api instagram
      description:  Returns TOKEN and stores it in redis server
      requestBody: 
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                password:
                  type: string
      responses:
        '200':
            description: OK

  /users:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses: 
        '201':
          description: Created
  /action:
    post: 
      summary: Perform a like/comment action on post
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties: 
                actionType: 
                  type: string
                postId:
                  type: string
      responses:
        '200':
          description: OK
                

  /ping:
    get:
      summary: Checks if the server is alive
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            format: uuid
          required: true