openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in HTML.
  version: 1.0.0
servers:
paths:
  /api/login:
    post:
      summary: login api instagram
      description:  Returns TOKEN and stores it in redis server
      requestBody: 
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
            description: OK
  /api/product-list:
    get:
      summary: Product Listing api
      description: GEt details wrt query params
      responses:
       '200':
          description: OK