openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in HTML.
  version: 1.0.0
servers:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only

paths:
  /api/login:
    post:
      summary: login api instagram
      description:  Returns TOKEN and stores it in redis server
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody: 
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
            description: OK
  /api/product-list:
    get:
      summary: Product Listing api
      description: Get details wrt query params
      responses:
        '200':
          description: OK
        
        